# Generated by Django 4.2.9 on 2024-12-27 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("package", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="packageorder",
            unique_together={("package", "order")},
        ),
        migrations.AddConstraint(
            model_name="packagedelivery",
            constraint=models.UniqueConstraint(
                fields=("package",), name="unique_package_delivery"
            ),
        ),
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("user", "number"), name="unique_user_package_number"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="package",
            unique_together={("user", "number")},
        ),
    ]
