# Generated by Django 4.2.9 on 2024-12-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0004_alter_packagedelivery_tracking_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="packagedelivery",
            name="tracking_number",
            field=models.CharField(
                max_length=100, verbose_name="Трек номер для отслеживания"
            ),
        ),
    ]
