# Generated by Django 4.2.9 on 2024-12-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("package", "0005_alter_packagedelivery_tracking_number"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="package",
            constraint=models.UniqueConstraint(
                fields=("user", "number"), name="unique_user_package_number"
            ),
        ),
    ]
