# Generated by Django 4.2.9 on 2024-12-24 18:43

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance_euro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Баланс в евро",
                    ),
                ),
                (
                    "balance_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Баланс в рублях",
                    ),
                ),
                (
                    "average_exchange_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Средний курс обмена",
                    ),
                ),
            ],
            options={
                "verbose_name": "Баланс",
                "verbose_name_plural": "Баланс",
                "permissions": [
                    ("can_change_balance", "Can change balance through transactions")
                ],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата транзакции",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Пополнение"),
                            ("expense", "Списание"),
                            ("payback", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "amount_euro",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма в евро",
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Сумма в рублях",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="balance.balance",
                        verbose_name="Баланс счета",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
                "ordering": ["-transaction_date"],
            },
        ),
        migrations.CreateModel(
            name="BalanceHistoryRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("replenishment", "Пополнение"),
                            ("expense", "Списание"),
                            ("payback", "Возврат"),
                        ],
                        max_length=20,
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "amount_euro",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Количество евро",
                    ),
                ),
                (
                    "amount_rub",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Количество рублей",
                    ),
                ),
                (
                    "amount_euro_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Количество евро после операции",
                    ),
                ),
                (
                    "amount_rub_after",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Количество рублей после операции",
                    ),
                ),
                (
                    "transaction_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата транзакции",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комменрий"),
                ),
                (
                    "balance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_history",
                        to="balance.balance",
                        verbose_name="Баланс счета",
                    ),
                ),
            ],
            options={
                "verbose_name": "История баланса",
                "verbose_name_plural": "История баланса",
                "ordering": ["-transaction_date"],
            },
        ),
    ]
