# Generated by Django 4.2.9 on 2025-01-24 23:42

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="transaction",
            name="positive_amount_euro",
        ),
        migrations.AlterField(
            model_name="balancehistoryrecord",
            name="amount_euro",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Количество евро",
            ),
        ),
        migrations.AlterField(
            model_name="balancehistoryrecord",
            name="amount_euro_after",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Количество евро после операции",
            ),
        ),
        migrations.AlterField(
            model_name="balancehistoryrecord",
            name="amount_rub",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Количество рублей",
            ),
        ),
        migrations.AlterField(
            model_name="balancehistoryrecord",
            name="amount_rub_after",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Количество рублей после операции",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_euro",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма в евро"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount_rub",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Сумма в рублях"
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="balance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transactions",
                to="balance.balance",
                verbose_name="Баланс",
            ),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Комментарий"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата транзакции"
            ),
        ),
    ]
