# Generated by Django 4.2.9 on 2024-12-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("status", "0001_initial"),
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(
                limit_choices_to={"group__code": "order_status"},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders_with_status",
                to="status.status",
                verbose_name="Статус заказа",
            ),
        ),
    ]
