# Generated by Django 4.2.9 on 2025-01-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_euro__gt", 0)), name="amount_euro_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("amount_rub__gt", 0)), name="amount_rub_positive"
            ),
        ),
    ]
