# Generated by Django 4.2.9 on 2025-01-22 21:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_order_amount_euro_positive_order_amount_rub_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateField(
                default=django.utils.timezone.localdate, verbose_name="Дата создания"
            ),
        ),
    ]
