# Generated by Django 4.2.9 on 2024-12-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Пользователь с таким email уже существует."},
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
